Processors:
  myFirstProcessor:
    BoostrapServer: localhost:9092
    GroupId: hellow
    Offset: latest
    Topic: hellow-world
    Concurrency: 1
    PollTimeout: 1000
    LogicContainer: logic.Printer