Processors:
  myFirstProcessor:
    BoostrapServer: localhost:9092
    GroupId: hellow
    Offset: latest
    Topic: hello_world
    Concurrency: 1
    PollTimeout: 1000
    Clazz: subject.LocalSubject
